#################################################################
##                                                             ##
##     /$$   /$$                              /$$              ##
##    | $$  | $$                             | $$              ##
##    | $$  | $$  /$$$$$$  /$$$$$$   /$$$$$$$| $$  /$$$$$$     ##
##    | $$  | $$ /$$__  $$|____  $$ /$$_____/| $$ /$$__  $$    ##
##    | $$  | $$| $$  \__/ /$$$$$$$| $$      | $$| $$$$$$$$    ##
##    | $$  | $$| $$      /$$__  $$| $$      | $$| $$_____/    ##
##    |  $$$$$$/| $$     |  $$$$$$$|  $$$$$$$| $$|  $$$$$$$    ##
##    \______/ |__/      \_______/ \_______/|__/ \_______/     ##
##                                     by unnamed_team         ##
##                                                             ##
#################################################################

# This is the configuration file for Uracle
# If you want to use special characters in this file, you must
# save the file using UTF-8



#################################################################
## +---------------------------------------------------------+ ##
## |                Resource Pack Metadata                   | ##
## +---------------------------------------------------------+ ##
#################################################################
metadata:
    # 6 -> 1.16
    # 7 .> 1.17
    format: 7
    description: |-
        &6MyServer Resource Pack
        Awesome



#################################################################
## +---------------------------------------------------------+ ##
## |            Resource Pack Generation Settings            | ##
## +---------------------------------------------------------+ ##
#################################################################

# How to generate resource pack?
# - mcpacks                -> upload to https://mc-packs.net/ (consider donating them)
# - polymath:<host>:<user> -> upload to a polymath server (authentication required)
# - zip                    -> generate zip file in plugin folder (resource-pack.zip)
# - folder                 -> generate resource-pack in a folder (resource-pack/)
generation: mcpacks



#################################################################
## +---------------------------------------------------------+ ##
## |           Resource Pack Application Settings            | ##
## +---------------------------------------------------------+ ##
#################################################################

# How to apply resource pack?
application:
    # Should the resource pack be forced to players?
    # (They will be kicked if they don't accept it)
    force: true

    # Message shown to players when they are prompted
    # to accept the resource pack (only if force: true)
    prompt: |-
        &c&lHey! &7You must accept our resource-pack
        &7to enjoy the full experience, are you ready?



#################################################################
## +---------------------------------------------------------+ ##
## |                         Messages                        | ##
## +---------------------------------------------------------+ ##
#################################################################
message:
    # Kick message sent when a player declines the resource-pack,
    # but it is required
    declined: |-
        &c&lUracle &8| &7by &d&lUnnamed Team
        &f
        &c&lHey!
        &7You must accept the server resource pack
        &7to join the server, enable it in the server
        &7list, check this tutorial:
        &d&nhttps://unnamed.team/uracle/player#enable
        &f
        &dThanks for playing!

    # Kick message sent when a player can not download the
    # resource-pack, but it is required
    failed: |-
        &c&lUracle &8| &7by &d&lUnnamed Team
        &f
        &c&lHey!
        &7Seems like your client has issues downloading
        &7the server resource pack, try re-joining or
        &7check this tutorial:
        &d&nhttps://unnamed.team/uracle/player#issues
        &f
        &dThanks for playing!

    # Message sent when a player executes /uracle, but they
    # have no permission to do it ('uracle' permission)
    permission: "&c&lUracle &8| &cError &8| &7You don't have permission to execute this command!"

    help: |-
        &c&lUracle &8| &7Help &8| &7by &d&lUnnamed Team
        &f
        &c/uracle help &8- &7Shows this message
        &c/uracle reload &8- &7Reload configuration
        &c/uracle apply [players...] &8- &7Sends the resource-pack to the specified players, or everyone if not specified



# Congratulations! You are done with configuration