load: STARTUP
main: team.unnamed.uracle.UraclePlugin
name: Uracle
version: 1.0.0
description: Library and API for next generation servers using resource packs
author: The Unnamed Team
website: https://unnamed.team/uracle
api-version: 1.13