##
##           the creative              /$$                        /$$
##                                    | $$                       | $$
##      /$$$$$$$  /$$$$$$  /$$$$$$$  /$$$$$$    /$$$$$$  /$$$$$$ | $$
##     /$$_____/ /$$__  $$| $$__  $$|_  $$_/   /$$__  $$|____  $$| $$
##    | $$      | $$$$$$$$| $$  \ $$  | $$    | $$  \__/ /$$$$$$$| $$
##    | $$      | $$_____/| $$  | $$  | $$ /$$| $$      /$$__  $$| $$
##    |  $$$$$$$|  $$$$$$$| $$  | $$  |  $$$$/| $$     |  $$$$$$$| $$
##    \_______/ \_______/|__/  |__/   \___/  |__/      \_______/|__/
##                                                  plugin by unnamed
##

##
## Settings for Resource Pack sending
##
send:
    request:
        # True to tell the player that they need to accept the resource-pack, false if the
        # resource-pack installation is optional
        #
        # IMPORTANT: Please note that this is purely client-side, the server will not necessarily
        #    kick the player if they don't accept the resource pack, you need to configure that in
        #    the 'feedback' section, specifically in the 'declined' section
        required: true

        # (Optional) Message shown to players when they join for the first time
        # They are asked to use the server resource pack and this message is
        # shown in the screen (1.17 and above, versions before 1.17 don't have this)
        prompt: '<green>Please accept the server resource pack'

    # Determines how much time to wait before sending the resource pack
    # to the player. Set to 0 or less to send immediately.
    delay: 0



##
## Specify what to do when the player accepts, declines or fails to
## download the server resource pack
##
feedback:
    accepted:
        - title:
              title: '<#ff8df8><bold>Welcome to the server!'
              subtitle: '<gray>Enjoy your stay!'
              fade-in: 10
              stay: 40
              fade-out: 10
        - message: '<green>You have accepted the resource pack!'
    declined:
        - kick: '<red>Please accept the server resource pack'
    failed:
        - kick: '<red>Failed to download the server resource pack'



##
## Settings for Resource Pack exporting
##
export:
    #
    # How should we export the generated resource pack?
    # |
    # |--> 'mcpacks' (default) (hosted)
    # |     Uploads the generated resource pack to https://mc-packs.net/,
    # |     a free resource pack hosting service (Consider donating to them)
    # |
    # |--> 'localhost' (hosted)
    # |     Opens a local HTTP server to serve resource packs, no third parties,
    # |     extra configuration is required (you need to open a new port in
    # |     your server)
    # |
    # |--> 'file' (non hosted)
    # |     Writes the generated resource pack to a ZIP file in the plugin
    # |     folder (/plugins/creative-central/output.zip)
    # |
    # |--> 'folder' (non hosted)
    # |     Writes the generated resource pack to a folder in the plugin
    # |     folder (/plugins/creative-central/output/)
    #
    # | Note: The plugin will not prompt players to download the resource
    # |       pack if the export method is not hosted, this is because
    # |       Minecraft requires an URL to be sent to the player in order
    # |       to download the resource pack
    type: 'mcpacks'

    # Configuration if type is 'localhost'
    localhost:
        # Put your server's public IP address or let the plugin
        # detect it by using an external "what is my ip" service
        # (See the --what-is-my-ip-services setting)
        address: ''

        # The resource pack host port
        port: 7270



##
## (ADVANCED AND INTERNAL SETTINGS)
## You probably don't want to touch anything below
##

# This setting specifies what "What is my ip" services we can use in order to obtain
# the server's IP address (which is sent to the client to download the resource pack)
--what-is-my-ip-services:
    - 'https://api.ipify.org'
    - 'https://api4.my-ip.io/ip'
    - 'https://api-ipv4.ip.sb/ip'